name: wbc-cnn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - opencv-python-headless=4.7.0.72
  - pillow=9.5.0
  - tqdm=4.65.0
  - jupyterlab=3.6.3
  - pip:
      - tensorflow==2.12.0
      - tensorflow-keras-vis==0.8.5       # optional (Grad-CAM / XAI)
      - tensorflow-addons==0.20.0         # optional (augmentation)
